/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dominio.Cliente;
import dominio.Cuenta;
import dominio.Transferencia;
import excepciones.PersistenciaException;
import implementaciones.ClientesDAO;
import implementaciones.CuentasDAO;
import implementaciones.TransferenciasDAO;
import interfaces.IClientesDAO;
import interfaces.IConexionBD;
import interfaces.ICuentasDAO;
import interfaces.ITransferenciasDAO;
import java.awt.event.ItemEvent;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge Sánchez y Rosalía Pérez
 */
public class TransferenciasForm extends javax.swing.JFrame {
private final IClientesDAO clientesDAO;
private final ICuentasDAO cuentasDAO;
private final ITransferenciasDAO transferenciasDAO;
private final Cliente cliente;
private final IConexionBD conexion;
    /**
     * Creates new form TransferenciasForm
     */
    public TransferenciasForm(IConexionBD conexion, Cliente cliente) {
        initComponents();
        this.conexion=conexion;
         this.clientesDAO =  new ClientesDAO(conexion);
         this.cuentasDAO = new CuentasDAO(conexion);
         this.transferenciasDAO = new TransferenciasDAO(conexion);
        this.cliente = cliente;
        System.out.println(cliente);
        this.llenarCombo();
    }

    
    public Transferencia extraerDatos(){
        Integer cuentaDestino = Integer.parseInt(this.txtfDestino.getText());
        Double montoTransferir = Double.parseDouble(this.txtfTransferir.getText());
        Cuenta origen = (Cuenta)cbxCuenta.getSelectedItem();
        Integer cuentaOrigen = origen.getNum_cuenta();;
        Transferencia transfer = new Transferencia(montoTransferir,cuentaOrigen,cuentaDestino);
        System.out.println(origen + "  " + cuentaOrigen + " " +transfer);
        return transfer;
    }
    
    public void transferir()throws PersistenciaException{
       try{
        Transferencia transferencia = this.extraerDatos();
        this.transferenciasDAO.hacerTransferencia(transferencia);
        this.mostrarMensajeTransferenciaHecha(transferencia);
       }catch(PersistenciaException ex){
           ex.getMessage();
           this.mostrarMensajeErrorAlTransferir();
       }
    }
    
    private void mostrarMensajeTransferenciaHecha(Transferencia transfer){
        JOptionPane.showMessageDialog(this, "Se realizó la transferencia" ,"Información",JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void mostrarMensajeErrorAlTransferir(){
        JOptionPane.showMessageDialog(this, "No fue posible transferir","Error",JOptionPane.ERROR_MESSAGE);
    }
    
    public void llenarCombo() {
        cbxCuenta.removeAllItems();
        try {
            List<Cuenta> cuentasAsociadas = cuentasDAO.consultarCombo(cliente);
            if (cuentasAsociadas == null) {
                this.btnTransferir.setEnabled(false);
            } else {
                this.btnTransferir.setEnabled(true);
                Iterator recorre = cuentasAsociadas.iterator();
                while (recorre.hasNext()) {
                    Cuenta cuenta = (Cuenta) recorre.next();
                    this.cbxCuenta.addItem(cuenta);
                }
            }
        } catch (PersistenciaException e) {
       JOptionPane.showMessageDialog(this, e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbxCuenta = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtfDestino = new javax.swing.JTextField();
        btnTransferir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtfTransferir = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transferencia");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(191, 218, 220));

        btnRegresar.setBackground(new java.awt.Color(89, 164, 232));
        btnRegresar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(26, 51, 89));
        jLabel2.setText("Cuentas");

        cbxCuenta.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbxCuenta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCuentaItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(26, 51, 89));
        jLabel5.setText("Cuenta destino");

        txtfDestino.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        btnTransferir.setBackground(new java.awt.Color(218, 81, 85));
        btnTransferir.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnTransferir.setForeground(new java.awt.Color(255, 255, 255));
        btnTransferir.setText("Transferir");
        btnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(26, 51, 89));
        jLabel6.setText("Monto a transferir");

        txtfTransferir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtfTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfTransferirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 51, 89));
        jLabel1.setText("Saldo de cuenta: $");

        lblSaldo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(97, 164, 127));
        jLabel4.setText("TRANSFERENCIA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(lblSaldo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cbxCuenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtfDestino)
                                    .addComponent(txtfTransferir)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnTransferir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                        .addComponent(btnRegresar))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel4)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblSaldo)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxCuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtfTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnTransferir))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
       if (this.txtfDestino.getText().isEmpty() || this.txtfTransferir.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los campos tienen que ser llenados");
        } else {
            try {
                this.transferir();
            } catch (PersistenciaException ex) {
                JOptionPane.showMessageDialog(null, "No se pudo ingresar el cliente");
            }
        }
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void cbxCuentaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCuentaItemStateChanged
//       if(evt.getStateChange()==ItemEvent.SELECTED){
//           
//       }
        Cuenta cuenta = (Cuenta)cbxCuenta.getSelectedItem();
        System.out.println(cuenta);
        if(cuenta != null){
            lblSaldo.setText(String.valueOf(cuenta.getSaldo()));
        }
    }//GEN-LAST:event_cbxCuentaItemStateChanged

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        MenuForm menu = new MenuForm(conexion,cliente);
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtfTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfTransferirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfTransferirActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnTransferir;
    private javax.swing.JComboBox<Cuenta> cbxCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTextField txtfDestino;
    private javax.swing.JTextField txtfTransferir;
    // End of variables declaration//GEN-END:variables
}
