CREATE DATABASE BANCO;
USE BANCO;

/*SCRIPT BUENO*/

CREATE TABLE DOMICILIO(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
CALLE VARCHAR (30) NOT NULL,
COLONIA VARCHAR (30) NOT NULL,
NUM_CASA VARCHAR (15) NOT NULL
);

CREATE TABLE CLIENTES(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NOMBRE VARCHAR (50) NOT NULL,
APELLIDO_PATERNO VARCHAR (50) NOT NULL,
APELLIDO_MATERNO VARCHAR (50) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
USUARIO VARCHAR(20) NOT NULL,
CONTRASENIA VARCHAR(16) NOT NULL,
ID_DOMICILIO INT NOT NULL,
FOREIGN KEY (ID_DOMICILIO) REFERENCES DOMICILIO(ID)
);

CREATE TABLE CUENTAS(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NUM_CUENTA INT,
SALDO DOUBLE,
FECHA_APERTURA DATETIME DEFAULT NOW(),
ID_CLIENTES INT NOT NULL,
FOREIGN KEY (ID_CLIENTES) REFERENCES CLIENTES(ID)
);


CREATE TABLE TRANSFERENCIAS(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
MONTO DOUBLE,
CUENTA_ORIGEN INT NOT NULL,
CUENTA_DESTINO INT NOT NULL,
FOREIGN KEY (CUENTA_DESTINO) REFERENCES CUENTAS(ID),
FOREIGN KEY (CUENTA_ORIGEN) REFERENCES CUENTAS(ID)
);

CREATE TABLE RETIRO_SIN_CUENTA(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
CUENTA_ORIGEN INT NOT NULL,
MONTO DOUBLE,
FOLIO INT NOT NULL,
CONTRASENIA VARCHAR(8) NOT NULL,
FOREIGN KEY (CUENTA_ORIGEN) REFERENCES CUENTAS(ID)
);


CREATE TABLE HISTORIAL(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
ID_OPERACION INT,
OPERACION VARCHAR(100),
FECHA DATETIME DEFAULT NOW(),
ID_CLIENTES INT NOT NULL,
FOREIGN KEY (ID_CLIENTES) REFERENCES CLIENTES(ID),
FOREIGN KEY (ID_OPERACION) REFERENCES TRANSFERENCIAS(ID),
FOREIGN KEY (ID_OPERACION) REFERENCES RETIRO_SIN_CUENTA(ID)
);

SELECT TRANSFERENCIAS.*, CUENTAS.SALDO
FROM TRANSFERENCIAS
INNER JOIN cuentas ON cuentas.ID = transferencias.CUENTA_DESTINO & cuentas.ID = transferencias.CUENTA_ORIGEN;
START TRANSACTION;
UPDATE CUENTAS 
SET saldo1 = CUENTAS.saldo - transferencias.monto
WHERE ID_TRANSFERENCIAS= '?';
UPDATE CUENTAS 
SET saldo2 = transferencias.saldo + transferencias.monto
WHERE ID_TRANSFERENCIAS= '?';
COMMIT;


DELIMITER $$
CREATE TRIGGER trigger_historial AFTER INSERT ON transferencias
FOR EACH ROW
BEGIN
        INSERT INTO historial (ID_operacion,transferencias,ID_clientes,fecha)
        VALUES(NEW.ID_operacion,transferencias,ID_clientes,NOW());
END;

DELIMITER $$
CREATE TRIGGER trigger_historial AFTER INSERT ON retiro_sin_cuenta
FOR EACH ROW
BEGIN
        INSERT INTO historial (ID_operacion,retiro_sin_cuenta,ID_clientes,fecha)
        VALUES(NEW.ID_operacion,NEW.retiro_sin_cuenta,NEW.ID_clientes,NOW());
END;



